# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 710f8bab123614dec3753adf0280b6e9ce044d67ccf8e514f548b6824f7d81fb51e449921ce6e04b868e775a7b9e8e6b101f37a909a78d62178e7ac20e9b99aa

test:
  secret_key_base: da7d8e606dadcebde22d564d63ea412259cefbc3065456628d94af0c41b30e5d09f5b5c781b10368668e8b784eb55283e2c93b31546a8037df33fe51066228ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
